
#*************** ptgrey_bfly_camera node and capture parameters ************************

#run mode: run mode: 0->SERVER, 1->PUBLISHER
run_mode: 1

#In case of PUBLISHER, the rate in hz.
#Video mode and pixel format may condition the final rate
rate: 10

#frame name of the camera
frame_name: "ptgrey_bfly_camera"

#file name of the camera calibration data, assumed to be at folder this_package/calibration
camera_info_file: "calibration_data_01.yaml"

#Video Mode (image size). Check camera documentation.
video_mode: 0

#Pixel Format: 0->MONO8, 1->RGB8.
pixel_format: 0
